N = readmatrix("Data\FullRunAnalysis.txt");

figure;
x = [0 1 2 3];
y = [...
    mean(N(N(:,1) == 0, 3)) mean(N(N(:,1) == 0, 4)) mean(N(N(:,1) == 0, 5)) mean(N(N(:,1) == 0, 6)) mean(N(N(:,1) == 0, 7)) mean(N(N(:,1) == 0, 8));...
    mean(N(N(:,1) == 1, 3)) mean(N(N(:,1) == 1, 4)) mean(N(N(:,1) == 1, 5)) mean(N(N(:,1) == 1, 6)) mean(N(N(:,1) == 1, 7)) mean(N(N(:,1) == 1, 8));...
    mean(N(N(:,1) == 2, 3)) mean(N(N(:,1) == 2, 4)) mean(N(N(:,1) == 2, 5)) mean(N(N(:,1) == 2, 6)) mean(N(N(:,1) == 2, 7)) mean(N(N(:,1) == 2, 8));...
    mean(N(N(:,1) == 3, 3)) mean(N(N(:,1) == 3, 4)) mean(N(N(:,1) == 3, 5)) mean(N(N(:,1) == 3, 6)) mean(N(N(:,1) == 3, 7)) mean(N(N(:,1) == 3, 8));...
    ];

barh(x,y);
hold on;
ylabel('Navigational Methods');
xlabel('Score');
legend({'Success','StepEfficiency','TimeEfficiency','ExplorationEfficiency','StepRedundancy','StepVisibility'});
set(gca, 'YTickLabel',{'Potential Field','PPF','AStar','RRT'});
hold off;

figure;
x = [0 1 2 3 4 5];
y = [...
    mean(N(N(:,1) == 0, 3)) mean(N(N(:,1) == 1, 3)) mean(N(N(:,1) == 2, 3)) mean(N(N(:,1) == 3, 3));...
    mean(N(N(:,1) == 0, 4)) mean(N(N(:,1) == 1, 4)) mean(N(N(:,1) == 2, 4)) mean(N(N(:,1) == 3, 4));...
    mean(N(N(:,1) == 0, 5)) mean(N(N(:,1) == 1, 5)) mean(N(N(:,1) == 2, 5)) mean(N(N(:,1) == 3, 5));...
    mean(N(N(:,1) == 0, 6)) mean(N(N(:,1) == 1, 6)) mean(N(N(:,1) == 2, 6)) mean(N(N(:,1) == 3, 6));...
    mean(N(N(:,1) == 0, 7)) mean(N(N(:,1) == 1, 7)) mean(N(N(:,1) == 2, 7)) mean(N(N(:,1) == 3, 7));...
    mean(N(N(:,1) == 0, 8)) mean(N(N(:,1) == 1, 8)) mean(N(N(:,1) == 2, 8)) mean(N(N(:,1) == 3, 8))...
    ];

barh(x,y);
hold on;
ylabel('Parameters');
xlabel('Score');
legend({'Potential Field','PPF','AStar','RRT'});
set(gca, 'YTickLabel',{'Success','StepEfficiency','TimeEfficiency','ExplorationEfficiency','StepRedundancy','StepVisibility'});
hold off;

figure;
x = [0 1 2 3];
y = [...
    mean( [ mean(N(N(:,1) == 0, 3)) mean(N(N(:,1) == 0, 4)) mean(N(N(:,1) == 0, 5)) ]);...
    mean( [ mean(N(N(:,1) == 1, 3)) mean(N(N(:,1) == 1, 4)) mean(N(N(:,1) == 1, 5)) ]);...
    mean( [ mean(N(N(:,1) == 2, 3)) mean(N(N(:,1) == 2, 4)) mean(N(N(:,1) == 2, 5)) ]);...
    mean( [ mean(N(N(:,1) == 3, 3)) mean(N(N(:,1) == 3, 4)) mean(N(N(:,1) == 3, 5)) ]);...
    ];

barh(x,y);
hold on;
ylabel('Navigational Methods');
xlabel('Score');
%legend({'Success','StepEfficiency','TimeEfficiency','ExplorationEfficiency','StepRedundancy','StepVisibility'});
set(gca, 'YTickLabel',{'Potential Field','PPF','AStar','RRT'});
hold off;
