%ObstacleRange,ObstacleConstant,AttractiveConstant,Counter,Constant,StrengthIncrease,Range
N = readmatrix("Data\PheromonePotentialField-Extensive-AllScatter.txt");

scatterRange(N(:,[1 2 4]), [0 10 15 25] ...
    ,'ObstacleRange', 'ObstacleConstant' ...
    ,[0 10], [0 10]);


scatterRange(N(:,[1 3 4]), [0 10 15 25] ...
    ,'ObstacleRange', 'AttractiveConstant' ...
    ,[0 10], [0 10]);

scatterRange(N(:,[2 3 4]), [0 10 15 25] ...
    ,'ObstacleConstant', 'AttractiveConstant' ...
    ,[0 10], [0 10]);